server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jwen1994/sprincloud-config.git
          search-paths:
            - springcloud-config
          username: xxxx@qq.com
          password: 111111
      label: master
  rabbitmq:
    host: 192.168.216.130
    port: 5672
    username: admin
    password: password

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"