server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.216.132:8848
#    alibaba:
#      seata:
#        tx-service-group: seata-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.216.132:3306/seata_order
    username: root
    password: 123456

seata:
  enabled: true
  application-id: seata-order-service
  # 事务群组（可以每个应用独立取名，也可以使用相同的名字），要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
  tx-service-group: abc-tx-group
  config:
    type: nacos
    # 需要和server在同一个注册中心下
    nacos:
      namespace: d52e8d91-7a2c-4f07-95de-083633fc31e3
      serverAddr: 192.168.216.132:8848
      # 需要server端(registry和config)、nacos配置client端(registry和config)保持一致
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      # 需要和server端保持一致，即server在nacos中的名称，默认为seata-server
      application: seata-server
      server-addr: 192.168.216.132:8848
      group: SEATA_GROUP
      namespace: d52e8d91-7a2c-4f07-95de-083633fc31e3
      username: nacos
      password: nacos

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
